export const goodsList = [
  {
    title:'花小肆 小众设计感学院风显',
    url:'../assets/close/1.jpg',
    price: '￥96',
    num: '已售10+',
    tab:'',
    tip:'',
  },{
    title:'奶系甜辣假两件麻花针织衫',
    url:'../assets/close/2.jpg',
    price: '￥75',
    num: '已售50+',
    tab:'',
    tip:'',
  },{
    title:'设计师的礼物原创樱花集国',
    url:'../assets/close/3.jpg',
    price: '',
    num: '',
    tab:'',
    tip:'满300减30',
  },{
    title:'INSstudios 糖果彩点肌理',
    url:'../assets/close/4.jpg',
    price: '￥99',
    num: '已售1000+',
    tab:'国货日',
    tip:'满300减30',
  },{
    title:'夏日热卖]御茶家甜心奶',
    url:'../assets/close/5.jpg',
    price: '￥138',
    num: '已售200+',
    tab:'',
    tip:'',
  },{
    title:'甜辣妹纯欲紫木耳边衬衫上',
    url:'../assets/close/6.jpg',
    price: '￥129',
    num: '已售1000+',
    tab:'国货日',
    tip:'每300减30',
  }, 
  {
  title:'不规则网纱吊带辣妹修身',
  url:'../assets/close/7.jpg',
  price: '￥78',
  num: '已售20+',
  tab:'国货日',
  tip:'每300减30',
},{
    title:'JEEP SPIRIT羽绒棉服女秋',
    url:'../assets/close/8.jpg',
    price: '￥99',
  num: '已售50+',
  tab:'国货日',
  tip:'每300减30',
  },{
    title:'【雾岛秋]jk毛呢牛角扣大衣',
    url:'../assets/close/9.jpg',
    price: '￥99',
    num: '已售50+',
    tab:'国货日',
    tip:'每300减30',
  },
]
